name: Publish Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on pushes to main
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build the demo code
  build:
    permissions:
      contents: read
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Check out the repository under $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Build ragged-blocks
        run: |
          npm ci
          npm run build

      - name: Build demo
        working-directory: ./demo
        run: |
          npm ci
          npm run build

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: demo/www/

  # Deploy the built demo code to GitHub pages
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
